using CardiTrack.API.Infrastructure.Auditing;
using CardiTrack.API.Infrastructure.UserContext;
using CardiTrack.Application.DTOs.Requests;
using CardiTrack.Application.DTOs.Responses;
using CardiTrack.Application.Interfaces.Services;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CardiTrack.API.Controllers;

/// <summary>
/// The questions the service has asked a family about a member, and what they answered.
/// </summary>
/// <remarks>
/// Answers are health information about the member, so every action here is access-checked against
/// the member and audited. Questions are generated by the AI pipeline, never by a request to this
/// controller — there is deliberately no "ask me something" endpoint.
/// </remarks>
[Authorize]
[AuditHealthDataAccess("ViewQuestionnaire")]
[Route("api/v1")]
public class QuestionnairesController : BaseApiController
{
    private readonly IQuestionnaireService _questionnaires;
    private readonly IValidator<AnswerQuestionnaireRequest> _answerValidator;

    public QuestionnairesController(
        IUserContext userContext,
        ILogger<QuestionnairesController> logger,
        IQuestionnaireService questionnaires,
        IValidator<AnswerQuestionnaireRequest> answerValidator)
        : base(userContext, logger)
    {
        _questionnaires = questionnaires;
        _answerValidator = answerValidator;
    }

    /// <summary>
    /// The pending question, and a page of the answered history newest first — optionally filtered
    /// to those whose question or answer text contains <paramref name="search"/>.
    /// </summary>
    [HttpGet("cardimembers/{cardiMemberId:guid}/questionnaires")]
    [ProducesResponseType(typeof(ApiResponse<QuestionnairesPageResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<QuestionnairesPageResponse>>> GetForMember(
        Guid cardiMemberId,
        [FromQuery] string? search,
        [FromQuery] int page,
        [FromQuery] int pageSize,
        CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        // Clamped rather than validated: this endpoint is a scroll position, not a form — an odd
        // page or pageSize from a client is worth correcting silently, not worth a 400 for.
        page = Math.Max(1, page == 0 ? 1 : page);
        pageSize = Math.Clamp(pageSize == 0 ? 20 : pageSize, 1, 50);

        try
        {
            var result = await _questionnaires.GetForMemberAsync(
                UserContext.UserId, cardiMemberId, search, page, pageSize, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>
    /// Answers a question, or replaces the answer already given — the same call either way.
    /// </summary>
    [HttpPut("questionnaires/{questionnaireId:guid}/answer")]
    [AuditHealthDataAccess("AnswerQuestionnaire")]
    [ProducesResponseType(typeof(ApiResponse<QuestionnaireResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<QuestionnaireResponse>>> Answer(
        Guid questionnaireId, [FromBody] AnswerQuestionnaireRequest request, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        var validation = await _answerValidator.ValidateAsync(request, ct);
        if (!validation.IsValid)
            return ValidationFailed(validation);

        try
        {
            var result = await _questionnaires.AnswerAsync(
                UserContext.UserId, questionnaireId, request.AnswerText, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>Skips the question. It is never asked again, and the record of asking survives.</summary>
    [HttpPut("questionnaires/{questionnaireId:guid}/dismiss")]
    [AuditHealthDataAccess("DismissQuestionnaire")]
    [ProducesResponseType(typeof(ApiResponse<QuestionnaireResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<QuestionnaireResponse>>> Dismiss(
        Guid questionnaireId, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            var result = await _questionnaires.DismissAsync(UserContext.UserId, questionnaireId, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>
    /// Removes the question and its answer. A real delete, not an archive — see
    /// <see cref="IQuestionnaireService.DeleteAsync"/>.
    /// </summary>
    [HttpDelete("questionnaires/{questionnaireId:guid}")]
    [AuditHealthDataAccess("DeleteQuestionnaire")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(Guid questionnaireId, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            await _questionnaires.DeleteAsync(UserContext.UserId, questionnaireId, ct);
            return NoContent();
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }
}
