using CardiTrack.API.Infrastructure.Auditing;
using CardiTrack.API.Infrastructure.UserContext;
using CardiTrack.Application.DTOs.Requests;
using CardiTrack.Application.DTOs.Responses;
using CardiTrack.Application.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CardiTrack.API.Controllers;

/// <summary>
/// The questions the service has asked a family about a member, and what they answered.
/// </summary>
/// <remarks>
/// Answers are health information about the member, so every action here is access-checked against
/// the member and audited. Questions are generated by the AI pipeline, never by a request to this
/// controller — there is deliberately no "ask me something" endpoint.
/// </remarks>
[Authorize]
[AuditHealthDataAccess("ViewQuestionnaire")]
[Route("api/v1")]
public class QuestionnairesController : BaseApiController
{
    private readonly IQuestionnaireService _questionnaires;

    public QuestionnairesController(
        IUserContext userContext,
        ILogger<QuestionnairesController> logger,
        IQuestionnaireService questionnaires)
        : base(userContext, logger)
    {
        _questionnaires = questionnaires;
    }

    /// <summary>Every question asked about this member, newest first, whatever became of it.</summary>
    [HttpGet("cardimembers/{cardiMemberId:guid}/questionnaires")]
    [ProducesResponseType(typeof(ApiResponse<IReadOnlyList<QuestionnaireResponse>>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<IReadOnlyList<QuestionnaireResponse>>>> GetForMember(
        Guid cardiMemberId, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            var result = await _questionnaires.GetForMemberAsync(UserContext.UserId, cardiMemberId, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>
    /// Answers a question, or replaces the answer already given — the same call either way.
    /// </summary>
    [HttpPut("questionnaires/{questionnaireId:guid}/answer")]
    [AuditHealthDataAccess("AnswerQuestionnaire")]
    [ProducesResponseType(typeof(ApiResponse<QuestionnaireResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<QuestionnaireResponse>>> Answer(
        Guid questionnaireId, [FromBody] AnswerQuestionnaireRequest request, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            var result = await _questionnaires.AnswerAsync(
                UserContext.UserId, questionnaireId, request.AnswerText, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>Skips the question. It is never asked again, and the record of asking survives.</summary>
    [HttpPut("questionnaires/{questionnaireId:guid}/dismiss")]
    [AuditHealthDataAccess("DismissQuestionnaire")]
    [ProducesResponseType(typeof(ApiResponse<QuestionnaireResponse>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ApiResponse<QuestionnaireResponse>>> Dismiss(
        Guid questionnaireId, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            var result = await _questionnaires.DismissAsync(UserContext.UserId, questionnaireId, ct);
            return Success(result);
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }

    /// <summary>
    /// Removes the question and its answer. A real delete, not an archive — see
    /// <see cref="IQuestionnaireService.DeleteAsync"/>.
    /// </summary>
    [HttpDelete("questionnaires/{questionnaireId:guid}")]
    [AuditHealthDataAccess("DeleteQuestionnaire")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(Guid questionnaireId, CancellationToken ct)
    {
        if (!UserContext.IsAuthenticated || UserContext.UserId == Guid.Empty)
        {
            return Error("We couldn't find your account — please sign in again.", StatusCodes.Status403Forbidden);
        }

        try
        {
            await _questionnaires.DeleteAsync(UserContext.UserId, questionnaireId, ct);
            return NoContent();
        }
        catch (KeyNotFoundException ex)
        {
            return Error(ex.Message, StatusCodes.Status404NotFound);
        }
    }
}
