using CardiTrack.Application.DTOs.Responses;

namespace CardiTrack.Application.Interfaces.Services;

public interface IHealthInsightService
{
    /// <summary>
    /// Analyses an alert for a CardiMember the requesting user is linked to.
    /// Throws <see cref="KeyNotFoundException"/> when the alert does not exist or the user
    /// may not view its CardiMember's health data — the two are indistinguishable by design.
    /// </summary>
    Task<AlertInsightResponse> AnalyzeAlertAsync(
        Guid requestingUserId, Guid alertId, CancellationToken ct = default);

    /// <summary>
    /// Analyses baseline trends for a CardiMember the requesting user is linked to.
    /// Throws <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<BaselineInsightResponse> AnalyzeBaselineAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// A general wellness suggestion for a CardiMember, grounded in their own readings and a fixed
    /// set of public-health wellness references — never a diagnosis or a treatment change.
    /// Read-only: the suggestion is generated by the pipeline's batch pass and persisted per
    /// member, so this serves the latest row and never calls the model. Throws
    /// <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<AdviseResponse> GetAdviseAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// A short, empathetic line describing a CardiMember's current status, for the Dashboard's
    /// hero card. Read-only: the line is generated by the pipeline's digest/assess passes and
    /// persisted per member, so a dashboard load costs one indexed lookup and never a model
    /// call. A null message means there is nothing (fresh enough) to say. Throws
    /// <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<CurrentStatusMessageResponse> GetCurrentStatusMessageAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);
}
