using CardiTrack.Application.DTOs.Responses;

namespace CardiTrack.Application.Interfaces.Services;

public interface IHealthInsightService
{
    /// <summary>
    /// The stored explanation of one alert, for a CardiMember the requesting user is linked to.
    /// Read-only: the explanation is written by the pipeline pass that raised the alert and
    /// persisted against it, so this never calls the model. An alert the pass has not reached
    /// comes back with empty text rather than an error. Throws
    /// <see cref="KeyNotFoundException"/> when the alert does not exist or the user may not view
    /// its CardiMember's health data — the two are indistinguishable by design.
    /// </summary>
    Task<AlertInsightResponse> AnalyzeAlertAsync(
        Guid requestingUserId, Guid alertId, CancellationToken ct = default);

    /// <summary>
    /// The stored reading of a CardiMember against their own baseline, with the learning and
    /// provisional states the dashboard shows. Read-only, as above — written by the digest pass.
    /// Throws <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<BaselineInsightResponse> AnalyzeBaselineAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// The stored trend narrative for a CardiMember the requesting user is linked to — the longer
    /// view, written by the daily trend pass. Read-only, like the two above. A member with under a
    /// month of readings comes back with empty text: that is the learning state, not a failure.
    /// Throws <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<TrendInsightResponse> GetTrendAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// Writes the explanation for one alert. Called by the pipeline pass that raised it, never
    /// from a request — there is no requesting user because there is no caregiver waiting.
    /// Returns whether a row was written; an alert already explained by the current brief, or one
    /// whose reply the register guards emptied, writes nothing.
    /// </summary>
    Task<bool> RegenerateAlertInsightAsync(Guid alertId, CancellationToken ct = default);

    /// <summary>
    /// Writes a CardiMember's reading against their own baseline, in the digest pass. Returns
    /// whether a row was written; a member whose insight is recent and written by the current
    /// brief is skipped before any model call.
    /// </summary>
    Task<bool> RegenerateBaselineInsightAsync(Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// A general wellness suggestion for a CardiMember, grounded in their own readings and a fixed
    /// set of public-health wellness references — never a diagnosis or a treatment change.
    /// Read-only: the suggestion is generated by the pipeline's batch pass and persisted per
    /// member, so this serves the latest row and never calls the model. Throws
    /// <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<AdviseResponse> GetAdviseAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);

    /// <summary>
    /// A short, empathetic line describing a CardiMember's current status, for the Dashboard's
    /// hero card. Read-only: the line is generated by the pipeline's digest/assess passes and
    /// persisted per member, so a dashboard load costs one indexed lookup and never a model
    /// call. A null message means there is nothing (fresh enough) to say. Throws
    /// <see cref="KeyNotFoundException"/> when the user may not view that member's health data.
    /// </summary>
    Task<CurrentStatusMessageResponse> GetCurrentStatusMessageAsync(
        Guid requestingUserId, Guid cardiMemberId, CancellationToken ct = default);
}
